name: 15 - Working with Matrices
on:
  workflow_dispatch
jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Perform some tests
        run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
  include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [ red, green ]
        shape: [ circle, square ]
        size: [ small, large ]
        include:
          - color: red
            shape: triangle
    steps:
      - name: Dummy step
        run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}"