name: 19 - 1 - Managing Concurrency
on:
  workflow_dispatch
concurrency:
  group: $GITHUB_WORKFLOW-$GITHUB_REF
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: https://www.somesite-ouyyfdclhjbi.com
          max_trials: 20
          delay: 5